language: cpp  # Travis-CI does not currently support Python and Mac OS X

os:
  - linux
  - osx

env:
  - PYTHON_VERSION=3.8
  - PYTHON_VERSION=3.9
  - PYTHON_VERSION=3.10

matrix:
  fast_finish: true
  allow_failures:
  - os: osx
  - env: PYTHON_VERSION=3.10

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda false --set notify_outdated_conda false
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$PYTHON_VERSION
  - conda activate test-environment
  - python --version

  - pip install coveralls PyYAML pytest pytest-cov wheel
  # for hyo2.abc2
  - conda install appdirs cartopy gdal matplotlib-base numpy psutil pyproj
  - pip install PySide6
  - pip install https://github.com/hydroffice/hyo2_abc/archive/master.zip
  # for hyo2.soundspeed
  - conda install gsw netCDF4 pillow pyserial scipy

  # --no-deps because of pip not detecting the installed hyo2.abc2
  - pip install --no-deps .
  - conda list --show-channel-urls

script:
  - coverage run --source hyo2 setup.py test
  - coverage report -m
  - coveralls

after_script:
  - python setup.py bdist_wheel

after_success:
  - path: dist\*

